CREATE TABLE IF NOT EXISTS user
(
    id       INT(64) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);